Filtering
ebzm/Surveys pull request #4
Opened 2022-06-16 10:56 UTC by ebzm

2022-06-16 12:09 UTC, IvanChibisov requested changes

2022-06-16 12:09 UTC, IvanChibisov commented on spec/graphql/queries/user_spec.rb
> +      let(:variables) { { "first" => user2.first_name, "last" => user2.last_name } }
Здесь лучше использовать строки вместо user2.first_name.
Проверь ещё, что у тебя двух юзеров вернет, если ты поищешь по `first_name: "Adam"`

2022-06-16 14:43 UTC, IvanChibisov requested changes

2022-06-16 14:49 UTC, ebzm commented on spec/graphql/queries/answer_spec.rb
> +    end
Тогда установится только то значение, которое передашь

2022-06-16 14:59 UTC, IvanChibisov commented on spec/graphql/queries/answer_spec.rb
> +    end
Нужно, чтобы min/max задавали промежуток, если передан, например, только `min` то вернуться должны только те `answer`(у тебя в 63 строке, кстати, опечатка :smile: ) у которых value не меньше `min`

2022-06-16 15:02 UTC, ebzm commented on spec/graphql/queries/answer_spec.rb
> +    end
Они и задают промежуток, но если один из них не указать, то будет от указанного, до крайнего допустимого значения (1 или 5)

2022-06-17 09:07 UTC, IvanChibisov requested changes
Прогони ещё рубокоп здесь(если он не поставлен в проект, то поставь). Также поставь rebocop-rspec

2022-06-17 09:07 UTC, IvanChibisov commented on app/graphql/types/query_type.rb
> +      scope = Filtering::Interval.extreme_values_filter(scope: scope, indicator: indicator, min: min, max: max)
Зачем тебе здесь :indicator? Что кроме answer_val может быть передано для answers?

2022-06-17 09:07 UTC, IvanChibisov commented on app/graphql/filtering/Interval.rb
> +        scope.select {|v| v if v.send(indicator.to_sym) <= max && v.send(indicator.to_sym) >= min}
Сделай это через ActiveRecord методы. У тебя массив возвращает сейчас, а должно ActiveRecord_Relation.

2022-06-17 11:10 UTC, IvanChibisov requested changes

2022-06-17 11:10 UTC, IvanChibisov commented on app/graphql/types/query_type.rb
> +      argument :max, Float, required: false, default_value: 5
Почему default_value 0 и 5? У тебя на модели ничем не ограничено это, поэтому не ограничивай дефолтами

2022-06-17 11:10 UTC, IvanChibisov commented on app/graphql/types/query_type.rb
> +      scope = Filtering::Interval.extreme_values_filter(scope: scope, indicator: indicator, min: min, max: max)
Тебе не нужна переменная indicator вообще для fields :answers.

2022-06-17 11:10 UTC, IvanChibisov commented on app/graphql/types/query_type.rb
> +      scope = Filtering::Interval.extreme_values_filter(scope: scope, indicator: indicator, min: min, max: max)
Назови метод не extreme_values_filter, а `filter_by_interval`

2022-06-17 11:10 UTC, IvanChibisov commented on spec/graphql/queries/user_spec.rb
> +  end
У тебя 2 одинаковых describe

2022-06-17 11:10 UTC, IvanChibisov commented on spec/graphql/queries/answer_spec.rb
> +  end
Давай ещё будет тест сразу для val, min и max )) Даже два теста, когда min..max включает val(там должно только с val остаться), и когда min..max не включает val(должен пустой массив прийти

2022-06-17 13:11 UTC, IvanChibisov requested changes

2022-06-17 13:11 UTC, IvanChibisov commented on spec/graphql/queries/user_spec.rb
> +    describe 'by first' do
допиши слово name)

2022-06-17 15:24 UTC, merged